#!/bin/sh -e

#DEBHELPER#

case "$1" in
    configure)
        # Old theme location
        update-alternatives --remove default.plymouth /lib/plymouth/themes/breeze/breeze.plymouth || true
        update-alternatives --remove text.plymouth /lib/plymouth/themes/breeze-text/breeze-text.plymouth || true
        # Remove old alternative (use plymouth-set-default-theme)
        update-alternatives --remove default.plymouth /usr/share/plymouth/themes/breeze/breeze.plymouth || true
        update-alternatives --remove text.plymouth /usr/share/plymouth/themes/breeze-text/breeze-text.plymouth || true
        ;;

    abort-upgrade|abort-deconfigure|abort-remove)
        ;;

    *)
        echo "$0 called with unknown argument \`$1'" 1>&2
        exit 1
        ;;
esac

exit 0
