#!/bin/sh -e

#DEBHELPER#

error()
{
    RET=$?
    MSG=$1
    echo "E: $MSG";
    exit $RET
}

if [ -e /usr/share/plymouth/themes/ ]; then
    THEMEDIR=/usr/share/plymouth/themes/
else
    THEMEDIR=/lib/plymouth/themes/
fi

case "$1" in
    configure)
        if [ -e /usr/share/plymouth/themes/ ]; then
            #plymouth themes moved here in xenial
            THEMEDIR=/usr/share/plymouth/themes/
            update-alternatives --remove default.plymouth /lib/plymouth/themes/breeze/breeze.plymouth || true
            update-alternatives --remove text.plymouth /lib/plymouth/themes/breeze-text/breeze-text.plymouth || true
        else
            THEMEDIR=/lib/plymouth/themes/
        fi

        update-alternatives \
            --install ${THEMEDIR}default.plymouth default.plymouth \
            ${THEMEDIR}breeze/breeze.plymouth 160 \
            --slave ${THEMEDIR}default.grub default.plymouth.grub \
            ${THEMEDIR}breeze/breeze.grub || error "Failed to update-alternatives"
        update-alternatives \
            --install ${THEMEDIR}text.plymouth text.plymouth \
            ${THEMEDIR}breeze-text/breeze-text.plymouth 160 \
            || error "Failed to update-alternatives text.plymouth"

        if which update-initramfs >/dev/null 2>&1; then
            update-initramfs -u || error "Failed to update-initramfs"
        fi

        if [ -e /boot/grub/grub.cfg ] && which update-grub2 >/dev/null 2>&1; then
            update-grub2 || error "Failed to update-grub2"
        fi
        ;;

    abort-upgrade|abort-deconfigure|abort-remove)
        ;;

    *)
        echo "$0 called with unknown argument \`$1'" 1>&2
        exit 1
        ;;
esac

exit 0
