#!/bin/sh -e

#DEBHELPER#

case "$1" in
    remove)
        # Old theme location
        update-alternatives --remove default.plymouth /lib/plymouth/themes/breeze/breeze.plymouth || true
        update-alternatives --remove text.plymouth /lib/plymouth/themes/breeze-text/breeze-text.plymouth || true
        # Remove old alternative (plymouth-set-default-theme)
        update-alternatives --remove default.plymouth /usr/share/plymouth/themes/breeze/breeze.plymouth || true
        update-alternatives --remove text.plymouth /lib/plymouth/themes/breeze-text/breeze-text.plymouth || true
        ;;

    purge)
        ;;

    upgrade|failed-upgrade|disappear)
        ;;

    abort-install|abort-upgrade)
        ;;

    *)
        echo "$0 called with unknown argument \`$1'" 1>&2
        exit 1
        ;;
esac

exit 0
